
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Java5TahminDB
    username: postgres
    password: 9896
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080